[package]
name = "reis"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
# calloop = { version = "0.10.5", optional = true } # TODO calloop source
rustix = { version = "0.37.19", features = ["net"] }

[dev-dependencies]
calloop = { version = "0.10.5" }

[patch.crates-io]
rustix = { path = "/home/ian/src/rustix" }
