[package]
name = "reis"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
# calloop = { version = "0.10.5", optional = true } # TODO calloop source
rustix = { version = "0.37.19", features = ["net"] }


[dev-dependencies]
calloop = { version = "0.10.5" }
once_cell = "1.17.1"

[patch.crates-io]
# TODO remove when merged
rustix = { git = "https://github.com/ids1024/rustix", branch = "fix-panic" }
