name: CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 1.65.0
        components: clippy, rustfmt
    - run: sudo apt-get -qq update
    - run: sudo apt-get install -y libxkbcommon-dev
    - run: cargo fmt --all -- --check
    - run: cargo clippy --all-features -- -Dwarnings
    - run: cargo build --all-features --examples
